[build]
  command = "npx playwright install chromium --with-deps && npm run build"
  publish = "dist"

[[redirects]]
  from = "/escuelas"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/familion"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/achala-viva"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/gondorbows"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/estadia"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/terminos-y-condiciones"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/politica-de-privacidad"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
