[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/escuelas"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/familion"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200